host = '192.168.1.3';	// hostname or IP address
port = 9001;
topic = 'house/#';		// topic to subscribe to
Caltopic = 'house/temp/calendar';		// topic to subscribe to
A1topic = 'house/temp/A1/sensor';		// topic to subscribe to
B1topic = 'house/temp/B1/sensor';		// topic to subscribe to
IMeantopic = 'house/temp/inside/weightedmean';
EMeantopic = 'house/temp/outside/weightedmean';
Outsidetopic = 'house/temp/weather';
Requesttopic = 'house/temp/userrequested';
Boilertopic = 'house/boiler/req';
useTLS = false;
username = null;
password = null;
cleansession = true;
